Fix error when opening recipe detail: TypeError: TuotteetPage.populate_product_list.<locals>.<lambda>() missing 1 required positional argument: 'checked'